-- DB2 SQL queries for reference --


-- Query physical file (only returns first record)
SELECT * FROM BOLIB.QCLLESRC;
SELECT * FROM BOLIB.QRPGLESRC;
SELECT * FROM BOLIB.QRPGSRC;
SELECT * FROM BOLIB.QDDSSRC;


-- Get all catalogs (databases) --
SELECT DISTINCT TABLE_CATALOG FROM QSYS2.TABLES ORDER BY TABLE_CATALOG ASC;


-- Get all schemas(libraries) --
SELECT DISTINCT SCHEMA_NAME FROM QSYS2.SYSSCHEMAS ORDER BY SCHEMA_NAME ASC;


-- Get all tables(physical files)
SELECT DISTINCT TABLE_NAME FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA = 'BOLIB';


-- Get all objects --
SELECT OBJNAME, OBJTYPE, OBJTEXT, OBJATTRIBUTE 
  FROM TABLE(QSYS2.OBJECT_STATISTICS('BOLIB','*ALL')) ORDER BY OBJNAME ASC;


-- Get all members using partition --
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_PARTITION, NUMBER_ROWS, DATA_SIZE, SOURCE_TYPE, PARTITION_TEXT
  FROM QSYS2.SYSPARTITIONSTAT WHERE TABLE_SCHEMA = 'BOLIB' ORDER BY TABLE_PARTITION;


-- Call CL Program from SQL --
CALL QSYS2.QCMDEXC('CALL BOLIB/FIRSTCL');


-- Get Member source (Works for RPGLE) --
CREATE OR REPLACE ALIAS QTEMP.BOSRCTMP FOR BOLIB.QRPGLESRC(FIZZBUZZ);
SELECT * FROM QTEMP.BOSRCTMP;
DROP ALIAS QTEMP.BOSRCTMP;

