-- DB2 SQL queries for reference --


-- Query physical file (only returns first record)
SELECT * FROM BOLIB.QCLLESRC;
SELECT * FROM BOLIB.QRPGLESRC;
SELECT * FROM BOLIB.QRPGSRC;
SELECT * FROM BOLIB.QDDSSRC;


-- Get all catalogs (databases) --
SELECT DISTINCT TABLE_CATALOG FROM QSYS2.TABLES ORDER BY TABLE_CATALOG ASC;


-- Get all schemas(libraries) --
SELECT DISTINCT SCHEMA_NAME FROM QSYS2.SYSSCHEMAS ORDER BY SCHEMA_NAME ASC;


-- Get all schemas in catalog --
SELECT DISTINCT TABLE_SCHEMA 
  FROM QSYS2.TABLES 
  WHERE TABLE_CATALOG = '<catalog>' 
  ORDER BY TABLE_SCHEMA ASC;


-- Get all tables in specific schema and catalog with additional columns --
WITH TABLES AS (
  SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ROW_NUMBER() 
    OVER (PARTITION BY TABLE_SCHEMA ORDER BY TABLE_SCHEMA) AS OCC
  FROM QSYS2.TABLES
) SELECT TABLE_SCHEMA, TABLE_TYPE 
    FROM TABLES 
    WHERE OCC = 1 AND TABLE_CATALOG='<catalog>' AND TABLE_SCHEMA='<schema>'
    ORDER BY TABLE_SCHEMA ASC;


-- Number of schemas in catalog --
SELECT COUNT(DISTINCT TABLE_SCHEMA) FROM QSYS2.TABLES WHERE TABLE_CATALOG='<catalog>';


-- Get all tables(physical files)
SELECT * FROM QSYS2.TABLES WHERE TABLE_CATALOG='<catalog>' AND TABLE_SCHEMA='BOLIB' ORDER BY TABLE_NAME ASC;


-- Get all objects --
SELECT OBJNAME, OBJTYPE, OBJTEXT, OBJATTRIBUTE 
  FROM TABLE(QSYS2.OBJECT_STATISTICS('BOLIB','*ALL')) ORDER BY OBJNAME ASC;


-- Get all members using partition --
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_PARTITION, NUMBER_ROWS, DATA_SIZE, SOURCE_TYPE, PARTITION_TEXT
  FROM QSYS2.SYSPARTITIONSTAT WHERE TABLE_SCHEMA = 'BOLIB' ORDER BY TABLE_PARTITION;


-- Call CL Program from SQL --
CALL QSYS2.QCMDEXC('CALL BOLIB/FIRSTCL');


-- Get Member source (Works for RPGLE) --
CREATE OR REPLACE ALIAS QTEMP.BOSRCTMP FOR BOLIB.QRPGLESRC(FIZZBUZZ);
SELECT * FROM QTEMP.BOSRCTMP;
DROP ALIAS QTEMP.BOSRCTMP;


-- Select all users in a database --
SELECT AUTHORIZATION_NAME, PREVIOUS_SIGNON, STATUS, PASSWORD_CHANGE_DATE, USER_CLASS_NAME, SPECIAL_AUTHORITIES, GROUP_PROFILE_NAME, OWNER, 
  TEXT_DESCRIPTION, STORAGE_USED, JOB_DESCRIPTION_NAME, JOB_DESCRIPTION_LIBRARY_NAME, MESSAGE_QUEUE_NAME, MESSAGE_QUEUE_LIBRARY_NAME, 
  OUTPUT_QUEUE_NAME, OUTPUT_QUEUE_LIBRARY_NAME, PRINT_DEVICE, USER_OPTIONS, USER_ID_NUMBER, GROUP_ID_NUMBER, HOME_DIRECTORY, DAYS_USED_COUNT
  FROM QSYS2.USER_INFO ORDER BY AUTHORIZATION_NAME ASC;