package com.barrettotte.ibmiapi.core;

public interface IAS400Statements{

  int DEFAULT_TIMEOUT_SECS = 10;

  String AS400_GET_CATALOGS = ""
    + "SELECT CATALOG_NAME,CATALOG_STATUS,CATALOG_TYPE,CATALOG_TEXT "
    +   "FROM QSYS2.SYSCATALOGS "
    +   "ORDER BY CATALOG_NAME ASC";

  String AS400_GET_CATALOG = "";

  String AS400_GET_SCHEMAS = ""
    + "SELECT DISTINCT TABLE_SCHEMA "
    +   "FROM QSYS2.TABLES "
    +   "WHERE TABLE_CATALOG = ? "
    +   "ORDER BY TABLE_SCHEMA ASC";

  String AS400_GET_SCHEMA = "";

  String AS400_GET_TABLES = ""
    + "SELECT TABLE_NAME, TABLE_TYPE "
    + "FROM QSYS2.TABLES "
    + "WHERE TABLE_CATALOG = ? AND TABLE_SCHEMA = ? "
    + "ORDER BY TABLE_NAME ASC";

  String AS400_GET_TABLE = "";

  String AS400_GET_PARTITIONS = ""
    + "SELECT SYSTEM_TABLE_MEMBER, PARTITION_NUMBER, NUMBER_ROWS, NUMBER_ROW_PAGES, NUMBER_PAGES " 
    + "DATA_SIZE, SOURCE_TYPE, PARTITION_TEXT, CREATE_TIMESTAMP, LAST_SAVE_TIMESTAMP "
    + "FROM QSYS2.SYSPARTITIONSTAT "
    + "WHERE TABLE_SCHEMA = ? AND TABLE_NAME=? "
    + "ORDER BY SYSTEM_TABLE_MEMBER ASC";
}